### ISSUE TITLE
Enhance layout for mobile devices

### ISSUE THREAD

**Issue by openscript** [timelet/timelet#31]
- [ ] (1) Fix container (dashboard)
- [ ] (2) Show creation dialog instead of inline form on small displays
- [ ] (3) Show the filters vertically (reporting)
- [ ] (4) Add horizontal scrolling to selected entries table (reporting)

![image](https://user-images.githubusercontent.com/1105080/109432861-8cc7cd00-7a0d-11eb-91d0-09686dc4426d.png)
![image](https://user-images.githubusercontent.com/1105080/109432900-bda80200-7a0d-11eb-8928-fb80c25d22dc.png)
![image](https://user-images.githubusercontent.com/1105080/109432907-c8629700-7a0d-11eb-86dc-678fd733f261.png)

**Comment by openscript** [comment]
Maybe something for @ralf-boltshauser ?

**Comment by ralf-boltshauser** [comment]
Yes, I will take it.
